- hosts: workers
  serial: 1
  remote_user: ubuntu
  tasks:
    - name: Copy Worker Kubeconfig
      copy:
        src: "../kubeconfig/worker-node/kubelet/worker-{{ groups['workers'].index(inventory_hostname) }}.kubeconfig"
        dest: "~/"
    - name: Copy Kubeproxy Kubeconfig
      copy:
        src: "../kubeconfig/worker-node/kube-proxy/kube-proxy.kubeconfig"
        dest: "~/"

- hosts: controllers
  remote_user: ubuntu
  tasks:
    - name: Copy Admin Kubeconfig
      copy:
        src: "../kubeconfig/admin-client/admin.kubeconfig"
        dest: "~/"
    - name: Copy Controller Manager Kubeconfig
      copy:
        src: "../kubeconfig/controller-node/controller-manager/kube-controller-manager.kubeconfig"
        dest: "~/"
    - name: Copy Kube Scheduler Kubeconfig
      copy:
        src: "../kubeconfig/controller-node/scheduler/kube-scheduler.kubeconfig"
        dest: "~/"
